on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 * * *"

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: covr

      - name: Test coverage
        run: |
            try(covr::package_coverage(clean = FALSE, quiet = FALSE, pre_clean = FALSE))
            file_list <- list.files("/tmp", recursive = TRUE)
            index <- grep("testthat.Rout.fail", file_list)
            print(file_list)
            cat(file = paste0("/tmp/", file_list[index]))
        shell: Rscript {0}

