on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 * * *"

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: covr

      - name: Test coverage
        run: |
          covr::package_coverage(clean = FALSE)

      - name: Show testthat output
        if: always()
        run: find -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash
